---Arabic alphabet configuration for Scrabble
---@return table<string, { count: number, points: number }>
return {
    ا = { count = 12, points = 1 },
    ب = { count = 4, points = 2 },
    ت = { count = 4, points = 2 },
    ث = { count = 2, points = 4 },
    ج = { count = 2, points = 4 },
    ح = { count = 2, points = 4 },
    خ = { count = 1, points = 8 },
    د = { count = 6, points = 1 },
    ذ = { count = 2, points = 4 },
    ر = { count = 6, points = 1 },
    ز = { count = 1, points = 8 },
    س = { count = 4, points = 2 },
    ش = { count = 2, points = 4 },
    ص = { count = 2, points = 4 },
    ض = { count = 1, points = 8 },
    ط = { count = 2, points = 4 },
    ظ = { count = 1, points = 8 },
    ع = { count = 6, points = 1 },
    غ = { count = 1, points = 8 },
    ف = { count = 4, points = 2 },
    ق = { count = 2, points = 4 },
    ك = { count = 4, points = 2 },
    ل = { count = 8, points = 1 },
    م = { count = 6, points = 1 },
    ن = { count = 8, points = 1 },
    ه = { count = 6, points = 1 },
    و = { count = 4, points = 2 },
    ي = { count = 6, points = 1 },
    ["*"] = { count = 2, points = 0 }
}
